# Generated by Django 5.1.2 on 2024-10-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber', '0003_alter_contacts_latitude_alter_contacts_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='iframe',
            field=models.TextField(default=1, verbose_name='Xarita iframeni kiriting'),
            preserve_default=False,
        ),
    ]
